export const questions = [
  "If you could have any superpower, what would it be and how would you use it?",
  "What's the most memorable trip you've ever taken?",
  "What's a skill you'd love to master in the next year?",
  "What's the best advice you've ever received?",
  "What's a hobby that you think everyone should try at least once?",
  "If you could instantly become an expert in any field, what would you choose?",
  "What's the most interesting documentary you've watched recently?",
  "What's a tradition from your culture or family that you really appreciate?",
  "What's the most challenging thing you've ever accomplished?",
  "If you could solve one global problem, what would it be?",
  "What's a book that changed your perspective on something?",
  "What's the most valuable life lesson you've learned so far?",
  "If you could have dinner with any historical figure, who would it be and why?",
  "What's a small act of kindness that someone did for you that you'll never forget?",
  "What's something you believed as a child that's amusing to you now?",
  "What's a place you've always wanted to visit and what draws you to it?",
  "What's the most interesting job you've ever heard of?",
  "What's a goal you're currently working towards?",
  "What's a technology advancement you hope to see in your lifetime?",
  "What's the most beautiful place you've ever been to?",
  "What's a skill you have that most people don't know about?",
  "What's a personal rule you live by?",
  "If you could master any musical instrument instantly, which would you choose?",
  "What's the most interesting conversation you've had recently?",
  "What's something you've changed your mind about over the years?",
  "What's a hobby or interest that you've had since childhood?",
  "What's the best piece of advice you'd give to your younger self?",
  "What's a random act of kindness you've done or witnessed recently?",
  "What's something you're looking forward to in the next year?",
  "What's a mistake you've made that taught you an important lesson?",
  "What's a book, movie, or show that you think everyone should experience?",
  "What's something you're proud of but don't often get to talk about?",
  "What's a question you've always wanted to ask but never had the chance?",
  "What's the most interesting place you've ever worked or studied?",
  "What's a culture or place you'd like to learn more about?",
  "What's a memory that always makes you laugh?",
  "What's something you think will be completely different in 10 years?",
  "What's the most interesting thing you've learned this year?",
  "What's a challenge you're glad you took on?",
  "What's something you wish more people knew about?",
  "What's a small thing that makes your day better?",
  "What's the most interesting thing about your job/studies?",
  "What's a story your family always tells about you?",
  "What's something you're grateful for that's easy to take for granted?",
  "What's a dream you're working towards?",
  "What's the best advice you've ever given someone?",
  "What's something you've recently discovered about yourself?",
  "What's a skill you'd like to learn just for fun?",
  "What's the most interesting food you've ever tried?",
  "What's a tradition you'd like to start?",
  "What's something that always cheers you up?",
  "What's the most interesting thing you've created?",
  "What's a subject you could talk about for hours?",
  "What's something you've done that surprised yourself?",
  "What's a place that exceeded your expectations?",
  "What's the most valuable thing you've learned from another culture?",
  "What's a current hobby you're really enjoying?",
  "What's something you're curious about but haven't explored yet?",
  "What's a compliment you've received that meant a lot to you?",
  "What's the most interesting thing about where you grew up?",
  "What's a belief you have that has changed over time?",
  "What's something you've accomplished that you're proud of?",
  "What's a problem you'd like to solve in your community?",
  "What's the most memorable concert or performance you've attended?",
  "What's something you learned the hard way?",
  "What's a small decision that ended up having a big impact?",
  "What's a place that holds special meaning for you?",
  "What's something you're passionate about that surprises people?",
  "What's the most interesting thing you've collected?",
  "What's a skill that has proven more valuable than you expected?",
  "What's something you wish you had known earlier in life?",
  "What's a tradition from another culture that you admire?",
  "What's the most challenging thing about your current goals?",
  "What's something that always motivates you?",
  "What's a book or movie that accurately portrays your profession?",
  "What's something you've changed your opinion about recently?",
  "What's a memorable experience that taught you something new?",
  "What's something you're better at than most people?",
  "What's a piece of technology that has significantly improved your life?",
  "What's something you've always wanted to try but haven't yet?",
  "What's the most interesting class you've ever taken?",
  "What's a skill that everyone should learn?",
  "What's something you wish you could experience again for the first time?",
  "What's a problem you recently solved in a creative way?",
  "What's something you've learned about yourself during challenging times?",
  "What's a place you find peaceful?",
  "What's something you're looking forward to learning more about?",
  "What's a project you're currently working on?",
  "What's something that recently made you change your perspective?",
  "What's a hobby that has taught you unexpected lessons?",
  "What's something you've done that you never thought you would?",
  "What's a question you think everyone should ask themselves?",
  "What's something you've recently become interested in?",
  "What's a memory that always makes you smile?",
  "What's something you're curious about in your field of work/study?",
  "What's a goal you achieved that surprised you?",
  "What's something you've learned from someone younger than you?",
  "What's a piece of advice that has stuck with you?",
  "What's something you do differently than most people?",
  "What's a story you'd like to tell your future self?",
  "What's something you've overcome that you're proud of?",
  "What's a question you love being asked?",
  "What's something that fascinates you about nature?",
  "What's a habit you're glad you developed?",
  "What's something you've learned from your mistakes?",
  "What's a dream you're currently pursuing?",
  "What's something you appreciate about your current stage of life?",
  "What's a lesson you keep learning over and over?",
];
